export const TYPES = {
  AUTOPOPULATE: "AUTOPOPULATE",
  AUTO_POPULATE_SUCCESS: "AUTO_POPULATE_SUCCESS",
  AUTO_POPULATE_FAILED: "AUTO_POPULATE_FAILED",
  SEARCH_BOOKS: "SEARCH_BOOKS",
  SEARCH_SUCCESS: "SEARCH_SUCCESS",
  SEARCH_FAILED: "SEARCH_FAILED",
  SEARCHING: "SEARCHING",
  AUTO_POPULATING: "AUTO_POPULATING",
  CLEAR_STATE: "CLEAR_STATE"
};
